### ISSUE TITLE
The Follow and the unfollow feature

### ISSUE THREAD

**Issue by baa215** [Intro-to-SE-Spring-21/Group-10#1]
This feature will allow the user to follow or unfollow other users. It will give them a choice if they would like to follow another user, and if they ever want to stop following that user they will be able to unfollow them.

Task:
Make a follow button.
After followed user make sure it says following.
When tapping on the button again it will unfollow the user.
If tapped again it will follow and repeat the process as needed.

**Comment by austinHarm** [comment]
Do you guys have any input on how we might implement this in code?
