### ISSUE TITLE
Functions

### ISSUE THREAD

**Issue by xxJLyricxx** [Intro-to-SE-Spring-21/Group-10#2]
One function that I want for this project is the ability to see how many likes you've gotten. Perhaps "all time likes"?

Task
Have a working like button.
When the user likes a picture a counter will tik up.
Counter is displayed on the homepage.
Counter will tik down if a like is removed.

**Comment by baa215** [comment]
This function will probably come later in the project, but this how got the thought going for a like button. Since this issue is about the all time like we will need to make a like button the user can use.

**Comment by baa215** [comment]
After making the like button, we will put this on the user home page, and show them how many likes they have gotten.

**Comment by austinHarm** [comment]
All time likes is an interesting idea. Something similar to Reddit karma?
